version: "3"

services:

 db:
   image: mongo:4.1.6
   ports:
     - "27017:27017"
   restart: always

 web:
   build:
     context: .
     dockerfile: Dockerfile
   ports:
     - "3000:3000"
   links:
     - db
   environment:
     - MONGO_HOST=db
     - MONGO_PORT=27017
     - MONGO_DATABASE_NAME=school
   command: node server.js
